        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:37 2013
        MODULE CGINIT__genmod
          INTERFACE 
            SUBROUTINE CGINIT(LOGCOM)
              LOGICAL(KIND=4) :: LOGCOM(6)
            END SUBROUTINE CGINIT
          END INTERFACE 
        END MODULE CGINIT__genmod
