        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:38 2013
        MODULE DTRETI__genmod
          INTERFACE 
            SUBROUTINE DTRETI(TSTRNG,IOPT,TIMESC)
              CHARACTER(*) :: TSTRNG
              INTEGER(KIND=4) :: IOPT
              REAL(KIND=4) :: TIMESC
            END SUBROUTINE DTRETI
          END INTERFACE 
        END MODULE DTRETI__genmod
