        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:28 2013
        MODULE GETKAR__genmod
          INTERFACE 
            SUBROUTINE GETKAR
            END SUBROUTINE GETKAR
          END INTERFACE 
        END MODULE GETKAR__genmod
