        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:28 2013
        MODULE LEESEL__genmod
          INTERFACE 
            SUBROUTINE LEESEL
            END SUBROUTINE LEESEL
          END INTERFACE 
        END MODULE LEESEL__genmod
