        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:28 2013
        MODULE NWLINE__genmod
          INTERFACE 
            SUBROUTINE NWLINE
            END SUBROUTINE NWLINE
          END INTERFACE 
        END MODULE NWLINE__genmod
