        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:38 2013
        MODULE STPNOW__genmod
          INTERFACE 
            FUNCTION STPNOW RESULT(STPNOW_0)
              LOGICAL(KIND=4) :: STPNOW_0
            END FUNCTION STPNOW
          END INTERFACE 
        END MODULE STPNOW__genmod
