        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:29 2013
        MODULE SWANGRIDTOPOLOGY__genmod
          INTERFACE 
            SUBROUTINE SWANGRIDTOPOLOGY
            END SUBROUTINE SWANGRIDTOPOLOGY
          END INTERFACE 
        END MODULE SWANGRIDTOPOLOGY__genmod
