        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:34 2013
        MODULE SWANPRINTGRIDINFO__genmod
          INTERFACE 
            SUBROUTINE SWANPRINTGRIDINFO
            END SUBROUTINE SWANPRINTGRIDINFO
          END INTERFACE 
        END MODULE SWANPRINTGRIDINFO__genmod
