        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:41 2013
        MODULE SWANREADGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADGRID
          END INTERFACE 
        END MODULE SWANREADGRID__genmod
