        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:27 2013
        MODULE SWANREADTRIANGLEGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADTRIANGLEGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADTRIANGLEGRID
          END INTERFACE 
        END MODULE SWANREADTRIANGLEGRID__genmod
