        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:43 2013
        MODULE SWANFINDPOINT__genmod
          INTERFACE 
            SUBROUTINE SWANFINDPOINT(X,Y,KVERT)
              REAL(KIND=4), INTENT(IN) :: X
              REAL(KIND=4), INTENT(IN) :: Y
              INTEGER(KIND=4), INTENT(OUT) :: KVERT
            END SUBROUTINE SWANFINDPOINT
          END INTERFACE 
        END MODULE SWANFINDPOINT__genmod
