        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:30 2013
        MODULE SWCOPR__genmod
          INTERFACE 
            SUBROUTINE SWCOPR(ARR1,ARR2,LENGTH)
              INTEGER(KIND=4) :: LENGTH
              REAL(KIND=4) :: ARR1(LENGTH)
              REAL(KIND=4) :: ARR2(LENGTH)
            END SUBROUTINE SWCOPR
          END INTERFACE 
        END MODULE SWCOPR__genmod
