        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:27 2013
        MODULE SWINITMPI__genmod
          INTERFACE 
            SUBROUTINE SWINITMPI
            END SUBROUTINE SWINITMPI
          END INTERFACE 
        END MODULE SWINITMPI__genmod
