        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:30 2013
        MODULE SWMAIN__genmod
          INTERFACE 
            SUBROUTINE SWMAIN
            END SUBROUTINE SWMAIN
          END INTERFACE 
        END MODULE SWMAIN__genmod
