        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:57:43 2013
        MODULE SWREOQ__genmod
          INTERFACE 
            SUBROUTINE SWREOQ(FOUND)
              LOGICAL(KIND=4) :: FOUND
            END SUBROUTINE SWREOQ
          END INTERFACE 
        END MODULE SWREOQ__genmod
