        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:07 2013
        MODULE COPYCH__genmod
          INTERFACE 
            SUBROUTINE COPYCH(STRING,MOVE,IARRAY,LENARR,IERR)
              CHARACTER(*) :: STRING
              CHARACTER(LEN=1) :: MOVE
              INTEGER(KIND=4) :: IARRAY(*)
              INTEGER(KIND=4) :: LENARR
              INTEGER(KIND=4) :: IERR
            END SUBROUTINE COPYCH
          END INTERFACE 
        END MODULE COPYCH__genmod
