        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:18 2013
        MODULE GETKAR__genmod
          INTERFACE 
            SUBROUTINE GETKAR
            END SUBROUTINE GETKAR
          END INTERFACE 
        END MODULE GETKAR__genmod
