        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:18 2013
        MODULE KEYWIS__genmod
          INTERFACE 
            FUNCTION KEYWIS(STRING) RESULT(KEYWIS_0)
              CHARACTER(*) :: STRING
              LOGICAL(KIND=4) :: KEYWIS_0
            END FUNCTION KEYWIS
          END INTERFACE 
        END MODULE KEYWIS__genmod
