        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:28 2013
        MODULE OCDTIM__genmod
          INTERFACE 
            SUBROUTINE OCDTIM(PRCTIM)
              INTEGER(KIND=4) :: PRCTIM(6)
            END SUBROUTINE OCDTIM
          END INTERFACE 
        END MODULE OCDTIM__genmod
