        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:28 2013
        MODULE SPROUT__genmod
          INTERFACE 
            SUBROUTINE SPROUT(FOUND,BOTLEV,WATLEV)
              LOGICAL(KIND=4) :: FOUND
              REAL(KIND=4) :: BOTLEV(*)
              REAL(KIND=4) :: WATLEV(*)
            END SUBROUTINE SPROUT
          END INTERFACE 
        END MODULE SPROUT__genmod
