        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:07 2013
        MODULE STPNOW__genmod
          INTERFACE 
            FUNCTION STPNOW RESULT(STPNOW_0)
              LOGICAL(KIND=4) :: STPNOW_0
            END FUNCTION STPNOW
          END INTERFACE 
        END MODULE STPNOW__genmod
