        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:07 2013
        MODULE STRACE__genmod
          INTERFACE 
            SUBROUTINE STRACE(IENT,SUBNAM)
              INTEGER(KIND=4) :: IENT
              CHARACTER(*) :: SUBNAM
            END SUBROUTINE STRACE
          END INTERFACE 
        END MODULE STRACE__genmod
