        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:29 2013
        MODULE SVARTP__genmod
          INTERFACE 
            SUBROUTINE SVARTP(IVTYPE)
              INTEGER(KIND=4) :: IVTYPE
            END SUBROUTINE SVARTP
          END INTERFACE 
        END MODULE SVARTP__genmod
