        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:32 2013
        MODULE SWANGRIDTOPOLOGY__genmod
          INTERFACE 
            SUBROUTINE SWANGRIDTOPOLOGY
            END SUBROUTINE SWANGRIDTOPOLOGY
          END INTERFACE 
        END MODULE SWANGRIDTOPOLOGY__genmod
