        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:23 2013
        MODULE SWANCREATEEDGES__genmod
          INTERFACE 
            SUBROUTINE SWANCREATEEDGES
            END SUBROUTINE SWANCREATEEDGES
          END INTERFACE 
        END MODULE SWANCREATEEDGES__genmod
