        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:09 2013
        MODULE SWANREADADCGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADADCGRID
            END SUBROUTINE SWANREADADCGRID
          END INTERFACE 
        END MODULE SWANREADADCGRID__genmod
