        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:30 2013
        MODULE SWANINTERPOLATEAC__genmod
          INTERFACE 
            SUBROUTINE SWANINTERPOLATEAC(ACINTP,X,Y,AC2,EXCPT)
              USE SWCOMM3
              USE SWANGRIDDATA
              REAL(KIND=4), INTENT(OUT) :: ACINTP(MDC,MSC)
              REAL(KIND=4), INTENT(IN) :: X
              REAL(KIND=4), INTENT(IN) :: Y
              REAL(KIND=4), INTENT(IN) :: AC2(MDC,MSC,NVERTS)
              LOGICAL(KIND=4), INTENT(OUT) :: EXCPT
            END SUBROUTINE SWANINTERPOLATEAC
          END INTERFACE 
        END MODULE SWANINTERPOLATEAC__genmod
