        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:14 2013
        MODULE SWANPRINTGRIDINFO__genmod
          INTERFACE 
            SUBROUTINE SWANPRINTGRIDINFO
            END SUBROUTINE SWANPRINTGRIDINFO
          END INTERFACE 
        END MODULE SWANPRINTGRIDINFO__genmod
