        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:28 2013
        MODULE SWANVERTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANVERTLIST
            END SUBROUTINE SWANVERTLIST
          END INTERFACE 
        END MODULE SWANVERTLIST__genmod
