        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:24 2013
        MODULE SWBLADM__genmod
          INTERFACE 
            SUBROUTINE SWBLADM(IPOWN,MXC,MYC)
              USE M_PARALL
              INTEGER(KIND=4) :: MYC
              INTEGER(KIND=4) :: MXC
              INTEGER(KIND=4) :: IPOWN(MXC,MYC)
            END SUBROUTINE SWBLADM
          END INTERFACE 
        END MODULE SWBLADM__genmod
