        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:32 2013
        MODULE SWCLME__genmod
          INTERFACE 
            SUBROUTINE SWCLME
            END SUBROUTINE SWCLME
          END INTERFACE 
        END MODULE SWCLME__genmod
