        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:24 2013
        MODULE SWDECOMP__genmod
          INTERFACE 
            SUBROUTINE SWDECOMP
            END SUBROUTINE SWDECOMP
          END INTERFACE 
        END MODULE SWDECOMP__genmod
