        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:24 2013
        MODULE SWEXCHG__genmod
          INTERFACE 
            SUBROUTINE SWEXCHG(FIELD,KGRPNT)
              USE SWCOMM3
              REAL(KIND=4) :: FIELD(MCGRD)
              INTEGER(KIND=4) :: KGRPNT(MXC*MYC)
            END SUBROUTINE SWEXCHG
          END INTERFACE 
        END MODULE SWEXCHG__genmod
