        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:24 2013
        MODULE SWEXITMPI__genmod
          INTERFACE 
            SUBROUTINE SWEXITMPI
            END SUBROUTINE SWEXITMPI
          END INTERFACE 
        END MODULE SWEXITMPI__genmod
