        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:24 2013
        MODULE SWINITMPI__genmod
          INTERFACE 
            SUBROUTINE SWINITMPI
            END SUBROUTINE SWINITMPI
          END INTERFACE 
        END MODULE SWINITMPI__genmod
