        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:31 2013
        MODULE SWMAIN__genmod
          INTERFACE 
            SUBROUTINE SWMAIN
            END SUBROUTINE SWMAIN
          END INTERFACE 
        END MODULE SWMAIN__genmod
