        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:29 2013
        MODULE SWNMPS__genmod
          INTERFACE 
            SUBROUTINE SWNMPS(PSNAME,PSTYPE,MIP,IERR)
              CHARACTER(*) :: PSNAME
              CHARACTER(LEN=1) :: PSTYPE
              INTEGER(KIND=4) :: MIP
              INTEGER(KIND=4) :: IERR
            END SUBROUTINE SWNMPS
          END INTERFACE 
        END MODULE SWNMPS__genmod
