        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:34 2013
        MODULE SWPRSET__genmod
          INTERFACE 
            SUBROUTINE SWPRSET(SPCSIG)
              USE SWCOMM3
              REAL(KIND=4) :: SPCSIG(MSC)
            END SUBROUTINE SWPRSET
          END INTERFACE 
        END MODULE SWPRSET__genmod
