        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:29 2013
        MODULE SWREOQ__genmod
          INTERFACE 
            SUBROUTINE SWREOQ(FOUND)
              LOGICAL(KIND=4) :: FOUND
            END SUBROUTINE SWREOQ
          END INTERFACE 
        END MODULE SWREOQ__genmod
