        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:19 2013
        MODULE SWREAD__genmod
          INTERFACE 
            SUBROUTINE SWREAD(COMPUT)
              CHARACTER(*) :: COMPUT
            END SUBROUTINE SWREAD
          END INTERFACE 
        END MODULE SWREAD__genmod
