        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:25 2013
        MODULE SWSNL1__genmod
          INTERFACE 
            SUBROUTINE SWSNL1(WWINT,WWAWG,WWSWG,IDCMIN,IDCMAX,UE,SA1,SA2&
     &,DA1C,DA1P,DA1M,DA2C,DA2P,DA2M,SPCSIG,SNLC1,KMESPC,FACHFR,ISSTOP, &
     &DAL1,DAL2,DAL3,SFNL,DSNL,DEP2,AC2,IMATDA,IMATRA,PLNL4S,PLNL4D,    &
     &IDDLOW,IDDTOP,REDC0,REDC1)
              USE SWCOMM3
              USE SWCOMM4
              INTEGER(KIND=4) :: WWINT(*)
              REAL(KIND=4) :: WWAWG(*)
              REAL(KIND=4) :: WWSWG(*)
              INTEGER(KIND=4) :: IDCMIN(MSC)
              INTEGER(KIND=4) :: IDCMAX(MSC)
              REAL(KIND=4) :: UE(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: SA1(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: SA2(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DA1C(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DA1P(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DA1M(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DA2C(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DA2P(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DA2M(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: SPCSIG(MSC)
              REAL(KIND=4) :: SNLC1
              REAL(KIND=4) :: KMESPC
              REAL(KIND=4) :: FACHFR
              INTEGER(KIND=4) :: ISSTOP
              REAL(KIND=4) :: DAL1
              REAL(KIND=4) :: DAL2
              REAL(KIND=4) :: DAL3
              REAL(KIND=4) :: SFNL(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DSNL(MSC4MI:MSC4MA,MDC4MI:MDC4MA)
              REAL(KIND=4) :: DEP2(MCGRD)
              REAL(KIND=4) :: AC2(MDC,MSC,MCGRD)
              REAL(KIND=4) :: IMATDA(MDC,MSC)
              REAL(KIND=4) :: IMATRA(MDC,MSC)
              REAL(KIND=4) :: PLNL4S(MDC,MSC,NPTST)
              REAL(KIND=4) :: PLNL4D(MDC,MSC,NPTST)
              INTEGER(KIND=4) :: IDDLOW
              INTEGER(KIND=4) :: IDDTOP
              REAL(KIND=4) :: REDC0(MDC,MSC,2)
              REAL(KIND=4) :: REDC1(MDC,MSC,2)
            END SUBROUTINE SWSNL1
          END INTERFACE 
        END MODULE SWSNL1__genmod
