        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 16:05:18 2013
        MODULE WRNKEY__genmod
          INTERFACE 
            SUBROUTINE WRNKEY
            END SUBROUTINE WRNKEY
          END INTERFACE 
        END MODULE WRNKEY__genmod
