        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:45 2013
        MODULE DEGCNV__genmod
          INTERFACE 
            FUNCTION DEGCNV(DEGREE) RESULT(DEGCNV_0)
              REAL(KIND=4) :: DEGREE
              REAL(KIND=4) :: DEGCNV_0
            END FUNCTION DEGCNV
          END INTERFACE 
        END MODULE DEGCNV__genmod
