        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:47 2013
        MODULE ERRCHK__genmod
          INTERFACE 
            SUBROUTINE ERRCHK
            END SUBROUTINE ERRCHK
          END INTERFACE 
        END MODULE ERRCHK__genmod
