        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:52 2013
        MODULE LEESEL__genmod
          INTERFACE 
            SUBROUTINE LEESEL
            END SUBROUTINE LEESEL
          END INTERFACE 
        END MODULE LEESEL__genmod
