        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:46 2013
        MODULE NUMSTR__genmod
          INTERFACE 
            FUNCTION NUMSTR(IVAL,RVAL,FORM) RESULT(NUMSTR_0)
              INTEGER(KIND=4) :: IVAL
              REAL(KIND=4) :: RVAL
              CHARACTER(LEN=20) :: FORM
              CHARACTER(LEN=20) :: NUMSTR_0
            END FUNCTION NUMSTR
          END INTERFACE 
        END MODULE NUMSTR__genmod
