        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:52 2013
        MODULE NWLINE__genmod
          INTERFACE 
            SUBROUTINE NWLINE
            END SUBROUTINE NWLINE
          END INTERFACE 
        END MODULE NWLINE__genmod
