        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:00 2013
        MODULE OCPINI__genmod
          INTERFACE 
            SUBROUTINE OCPINI(INIFIL,LREAD,INERR)
              CHARACTER(*) :: INIFIL
              LOGICAL(KIND=4) :: LREAD
              INTEGER(KIND=4) :: INERR
            END SUBROUTINE OCPINI
          END INTERFACE 
        END MODULE OCPINI__genmod
