        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:58 2013
        MODULE SREDEP__genmod
          INTERFACE 
            SUBROUTINE SREDEP(LWINDR,LWINDM,LOGCOM)
              INTEGER(KIND=4) :: LWINDR
              INTEGER(KIND=4) :: LWINDM
              LOGICAL(KIND=4) :: LOGCOM(6)
            END SUBROUTINE SREDEP
          END INTERFACE 
        END MODULE SREDEP__genmod
