        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:54 2013
        MODULE SWANBPNTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANBPNTLIST
            END SUBROUTINE SWANBPNTLIST
          END INTERFACE 
        END MODULE SWANBPNTLIST__genmod
