        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:50 2013
        MODULE SWANPOINTINMESH__genmod
          INTERFACE 
            FUNCTION SWANPOINTINMESH(X,Y) RESULT(SWANPOINTINMESH_0)
              REAL(KIND=4), INTENT(IN) :: X
              REAL(KIND=4), INTENT(IN) :: Y
              LOGICAL(KIND=4) :: SWANPOINTINMESH_0
            END FUNCTION SWANPOINTINMESH
          END INTERFACE 
        END MODULE SWANPOINTINMESH__genmod
