        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:02 2013
        MODULE SWANCROSSOBSTACLE__genmod
          INTERFACE 
            FUNCTION SWANCROSSOBSTACLE(XV,YV,XOBS,YOBS) RESULT(         &
     &SWANCROSSOBSTACLE_0)
              REAL(KIND=4), INTENT(IN) :: XV(2)
              REAL(KIND=4), INTENT(IN) :: YV(2)
              REAL(KIND=4), INTENT(IN) :: XOBS(2)
              REAL(KIND=4), INTENT(IN) :: YOBS(2)
              LOGICAL(KIND=4) :: SWANCROSSOBSTACLE_0
            END FUNCTION SWANCROSSOBSTACLE
          END INTERFACE 
        END MODULE SWANCROSSOBSTACLE__genmod
