        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:44 2013
        MODULE SWANREADADCGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADADCGRID
            END SUBROUTINE SWANREADADCGRID
          END INTERFACE 
        END MODULE SWANREADADCGRID__genmod
