        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:06 2013
        MODULE SWANINITCOMPGRID__genmod
          INTERFACE 
            SUBROUTINE SWANINITCOMPGRID(LOGCOM)
              LOGICAL(KIND=4), INTENT(INOUT) :: LOGCOM(6)
            END SUBROUTINE SWANINITCOMPGRID
          END INTERFACE 
        END MODULE SWANINITCOMPGRID__genmod
