        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:50 2013
        MODULE SWANPRINTGRIDINFO__genmod
          INTERFACE 
            SUBROUTINE SWANPRINTGRIDINFO
            END SUBROUTINE SWANPRINTGRIDINFO
          END INTERFACE 
        END MODULE SWANPRINTGRIDINFO__genmod
