        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:56 2013
        MODULE SWANFINDOBSTACLES__genmod
          INTERFACE 
            SUBROUTINE SWANFINDOBSTACLES(CROSS)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(OUT) :: CROSS(NFACES)
            END SUBROUTINE SWANFINDOBSTACLES
          END INTERFACE 
        END MODULE SWANFINDOBSTACLES__genmod
