        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:46 2013
        MODULE SWCOPI__genmod
          INTERFACE 
            SUBROUTINE SWCOPI(IARR1,IARR2,LENGTH)
              INTEGER(KIND=4) :: LENGTH
              INTEGER(KIND=4) :: IARR1(LENGTH)
              INTEGER(KIND=4) :: IARR2(LENGTH)
            END SUBROUTINE SWCOPI
          END INTERFACE 
        END MODULE SWCOPI__genmod
