        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:12 2013
        MODULE SWDECOMP__genmod
          INTERFACE 
            SUBROUTINE SWDECOMP
            END SUBROUTINE SWDECOMP
          END INTERFACE 
        END MODULE SWDECOMP__genmod
