        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:12 2013
        MODULE SWEXITMPI__genmod
          INTERFACE 
            SUBROUTINE SWEXITMPI
            END SUBROUTINE SWEXITMPI
          END INTERFACE 
        END MODULE SWEXITMPI__genmod
