        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:12 2013
        MODULE SWINITMPI__genmod
          INTERFACE 
            SUBROUTINE SWINITMPI
            END SUBROUTINE SWINITMPI
          END INTERFACE 
        END MODULE SWINITMPI__genmod
