        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:46 2013
        MODULE SWINIT__genmod
          INTERFACE 
            SUBROUTINE SWINIT(INERR)
              INTEGER(KIND=4) :: INERR
            END SUBROUTINE SWINIT
          END INTERFACE 
        END MODULE SWINIT__genmod
