        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:11:12 2013
        MODULE SWSYNC__genmod
          INTERFACE 
            SUBROUTINE SWSYNC
            END SUBROUTINE SWSYNC
          END INTERFACE 
        END MODULE SWSYNC__genmod
