        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 29 12:10:52 2013
        MODULE UPCASE__genmod
          INTERFACE 
            SUBROUTINE UPCASE(CHARST)
              CHARACTER(*) :: CHARST
            END SUBROUTINE UPCASE
          END INTERFACE 
        END MODULE UPCASE__genmod
