        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:04 2012
        MODULE BUGFIX__genmod
          INTERFACE 
            SUBROUTINE BUGFIX(FIXABC)
              CHARACTER(LEN=1), INTENT(IN) :: FIXABC
            END SUBROUTINE BUGFIX
          END INTERFACE 
        END MODULE BUGFIX__genmod
