        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:57 2012
        MODULE CGINIT__genmod
          INTERFACE 
            SUBROUTINE CGINIT(LOGCOM)
              LOGICAL(KIND=4) :: LOGCOM(6)
            END SUBROUTINE CGINIT
          END INTERFACE 
        END MODULE CGINIT__genmod
