        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:04 2012
        MODULE DIFPAR__genmod
          INTERFACE 
            SUBROUTINE DIFPAR(AC2,SPCSIG,KGRPNT,DEP2,CROSS,XCGRID,YCGRID&
     &,XYTST)
              USE SWCOMM3
              REAL(KIND=4), INTENT(INOUT) :: AC2(MDC,MSC,MCGRD)
              REAL(KIND=4), INTENT(IN) :: SPCSIG(MSC)
              INTEGER(KIND=4), INTENT(IN) :: KGRPNT(MXC,MYC)
              REAL(KIND=4), INTENT(IN) :: DEP2(MCGRD)
              REAL(KIND=4), INTENT(IN) :: CROSS(2,MCGRD)
              REAL(KIND=4), INTENT(IN) :: XCGRID(MXC,MYC)
              REAL(KIND=4), INTENT(IN) :: YCGRID(MXC,MYC)
              INTEGER(KIND=4), INTENT(IN) :: XYTST(*)
            END SUBROUTINE DIFPAR
          END INTERFACE 
        END MODULE DIFPAR__genmod
