        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE EQCSTR__genmod
          INTERFACE 
            FUNCTION EQCSTR(STR1,STR2) RESULT(EQCSTR_0)
              CHARACTER(*) :: STR1
              CHARACTER(*) :: STR2
              LOGICAL(KIND=4) :: EQCSTR_0
            END FUNCTION EQCSTR
          END INTERFACE 
        END MODULE EQCSTR__genmod
