        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE IGNORE__genmod
          INTERFACE 
            SUBROUTINE IGNORE(STRING)
              CHARACTER(*) :: STRING
            END SUBROUTINE IGNORE
          END INTERFACE 
        END MODULE IGNORE__genmod
