        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:57 2012
        MODULE INITVA__genmod
          INTERFACE 
            SUBROUTINE INITVA(AC2,SPCSIG,SPCDIR,KGRPNT)
              USE SWCOMM3
              REAL(KIND=4) :: AC2(MDC,MSC,MCGRD)
              REAL(KIND=4) :: SPCSIG(MSC)
              REAL(KIND=4) :: SPCDIR(MDC,6)
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
            END SUBROUTINE INITVA
          END INTERFACE 
        END MODULE INITVA__genmod
