        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE KEYWIS__genmod
          INTERFACE 
            FUNCTION KEYWIS(STRING) RESULT(KEYWIS_0)
              CHARACTER(*) :: STRING
              LOGICAL(KIND=4) :: KEYWIS_0
            END FUNCTION KEYWIS
          END INTERFACE 
        END MODULE KEYWIS__genmod
