        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:57 2012
        MODULE SEPARAREA__genmod
          INTERFACE 
            SUBROUTINE SEPARAREA(IX,IY,KGRPNT,IDIR)
              USE SWCOMM3
              INTEGER(KIND=4) :: IX
              INTEGER(KIND=4) :: IY
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
              INTEGER(KIND=4) :: IDIR
            END SUBROUTINE SEPARAREA
          END INTERFACE 
        END MODULE SEPARAREA__genmod
