        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:57 2012
        MODULE SSFILL__genmod
          INTERFACE 
            SUBROUTINE SSFILL(SPCSIG,SPCDIR)
              USE SWCOMM3
              REAL(KIND=4) :: SPCSIG(MSC)
              REAL(KIND=4) :: SPCDIR(MDC,6)
            END SUBROUTINE SSFILL
          END INTERFACE 
        END MODULE SSFILL__genmod
