        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:04 2012
        MODULE STRACE__genmod
          INTERFACE 
            SUBROUTINE STRACE(IENT,SUBNAM)
              INTEGER(KIND=4) :: IENT
              CHARACTER(*) :: SUBNAM
            END SUBROUTINE STRACE
          END INTERFACE 
        END MODULE STRACE__genmod
