        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:01 2012
        MODULE SWANBPNTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANBPNTLIST
            END SUBROUTINE SWANBPNTLIST
          END INTERFACE 
        END MODULE SWANBPNTLIST__genmod
