        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:05 2012
        MODULE SWANDIFFPAR__genmod
          INTERFACE 
            SUBROUTINE SWANDIFFPAR(AC2,DEP2,SPCSIG)
              USE SWCOMM3
              USE SWANGRIDDATA
              REAL(KIND=4), INTENT(IN) :: AC2(MDC,MSC,NVERTS)
              REAL(KIND=4), INTENT(IN) :: DEP2(NVERTS)
              REAL(KIND=4), INTENT(IN) :: SPCSIG(MSC)
            END SUBROUTINE SWANDIFFPAR
          END INTERFACE 
        END MODULE SWANDIFFPAR__genmod
