        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE SWANGRIDVERT__genmod
          INTERFACE 
            SUBROUTINE SWANGRIDVERT(NVERTS,XCUGRD,YCUGRD,VMARK)
              INTEGER(KIND=4), INTENT(IN) :: NVERTS
              REAL(KIND=4), INTENT(IN) :: XCUGRD(NVERTS)
              REAL(KIND=4), INTENT(IN) :: YCUGRD(NVERTS)
              INTEGER(KIND=4), INTENT(IN) :: VMARK(NVERTS)
            END SUBROUTINE SWANGRIDVERT
          END INTERFACE 
        END MODULE SWANGRIDVERT__genmod
