        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE SWCOPR__genmod
          INTERFACE 
            SUBROUTINE SWCOPR(ARR1,ARR2,LENGTH)
              INTEGER(KIND=4) :: LENGTH
              REAL(KIND=4) :: ARR1(LENGTH)
              REAL(KIND=4) :: ARR2(LENGTH)
            END SUBROUTINE SWCOPR
          END INTERFACE 
        END MODULE SWCOPR__genmod
