        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWEXITMPI__genmod
          INTERFACE 
            SUBROUTINE SWEXITMPI
            END SUBROUTINE SWEXITMPI
          END INTERFACE 
        END MODULE SWEXITMPI__genmod
