        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWREDUCI__genmod
          INTERFACE 
            SUBROUTINE SWREDUCI(IARR,ILEN,ITYPRD)
              INTEGER(KIND=4) :: ILEN
              INTEGER(KIND=4) :: IARR(ILEN)
              INTEGER(KIND=4) :: ITYPRD
            END SUBROUTINE SWREDUCI
          END INTERFACE 
        END MODULE SWREDUCI__genmod
