        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:01 2012
        MODULE SWREPS__genmod
          INTERFACE 
            SUBROUTINE SWREPS(FOUND,BOTLEV,WATLEV)
              LOGICAL(KIND=4) :: FOUND
              REAL(KIND=4) :: BOTLEV(*)
              REAL(KIND=4) :: WATLEV(*)
            END SUBROUTINE SWREPS
          END INTERFACE 
        END MODULE SWREPS__genmod
