        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:33 2013
        MODULE BUGFIX__genmod
          INTERFACE 
            SUBROUTINE BUGFIX(FIXABC)
              CHARACTER(LEN=1), INTENT(IN) :: FIXABC
            END SUBROUTINE BUGFIX
          END INTERFACE 
        END MODULE BUGFIX__genmod
