        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:21 2013
        MODULE CGBOUN__genmod
          INTERFACE 
            SUBROUTINE CGBOUN(KGRPNT,KGRBND)
              USE SWCOMM3
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
              INTEGER(KIND=4) :: KGRBND(*)
            END SUBROUTINE CGBOUN
          END INTERFACE 
        END MODULE CGBOUN__genmod
