        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:33 2013
        MODULE COPYCH__genmod
          INTERFACE 
            SUBROUTINE COPYCH(STRING,MOVE,IARRAY,LENARR,IERR)
              CHARACTER(*) :: STRING
              CHARACTER(LEN=1) :: MOVE
              INTEGER(KIND=4) :: IARRAY(*)
              INTEGER(KIND=4) :: LENARR
              INTEGER(KIND=4) :: IERR
            END SUBROUTINE COPYCH
          END INTERFACE 
        END MODULE COPYCH__genmod
