        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:33 2013
        MODULE DTINTI__genmod
          INTERFACE 
            SUBROUTINE DTINTI(TIMESC,INTTIM)
              REAL(KIND=4) :: TIMESC
              INTEGER(KIND=4) :: INTTIM(6)
            END SUBROUTINE DTINTI
          END INTERFACE 
        END MODULE DTINTI__genmod
