        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:33 2013
        MODULE DTRETI__genmod
          INTERFACE 
            SUBROUTINE DTRETI(TSTRNG,IOPT,TIMESC)
              CHARACTER(*) :: TSTRNG
              INTEGER(KIND=4) :: IOPT
              REAL(KIND=4) :: TIMESC
            END SUBROUTINE DTRETI
          END INTERFACE 
        END MODULE DTRETI__genmod
