        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:23 2013
        MODULE DTSTTI__genmod
          INTERFACE 
            SUBROUTINE DTSTTI(IOPT,TIMSTR,DTTIME)
              INTEGER(KIND=4) :: IOPT
              CHARACTER(LEN=24) :: TIMSTR
              INTEGER(KIND=4) :: DTTIME(6)
            END SUBROUTINE DTSTTI
          END INTERFACE 
        END MODULE DTSTTI__genmod
