        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:44 2013
        MODULE INTSTR__genmod
          INTERFACE 
            FUNCTION INTSTR(IVAL) RESULT(INTSTR_0)
              INTEGER(KIND=4) :: IVAL
              CHARACTER(LEN=20) :: INTSTR_0
            END FUNCTION INTSTR
          END INTERFACE 
        END MODULE INTSTR__genmod
