        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:23 2013
        MODULE OCDTIM__genmod
          INTERFACE 
            SUBROUTINE OCDTIM(PRCTIM)
              INTEGER(KIND=4) :: PRCTIM(6)
            END SUBROUTINE OCDTIM
          END INTERFACE 
        END MODULE OCDTIM__genmod
