        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:23 2013
        MODULE OCPINI__genmod
          INTERFACE 
            SUBROUTINE OCPINI(INIFIL,LREAD,INERR)
              CHARACTER(*) :: INIFIL
              LOGICAL(KIND=4) :: LREAD
              INTEGER(KIND=4) :: INERR
            END SUBROUTINE OCPINI
          END INTERFACE 
        END MODULE OCPINI__genmod
