        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:21 2013
        MODULE SEPARAREA__genmod
          INTERFACE 
            SUBROUTINE SEPARAREA(IX,IY,KGRPNT,IDIR)
              USE SWCOMM3
              INTEGER(KIND=4) :: IX
              INTEGER(KIND=4) :: IY
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
              INTEGER(KIND=4) :: IDIR
            END SUBROUTINE SEPARAREA
          END INTERFACE 
        END MODULE SEPARAREA__genmod
