        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:20 2013
        MODULE SINPGR__genmod
          INTERFACE 
            SUBROUTINE SINPGR(IGRID1,IGRID2,SNAMEG)
              INTEGER(KIND=4) :: IGRID1
              INTEGER(KIND=4) :: IGRID2
              CHARACTER(LEN=8) :: SNAMEG
            END SUBROUTINE SINPGR
          END INTERFACE 
        END MODULE SINPGR__genmod
