        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:20 2013
        MODULE SREDEP__genmod
          INTERFACE 
            SUBROUTINE SREDEP(LWINDR,LWINDM,LOGCOM)
              INTEGER(KIND=4) :: LWINDR
              INTEGER(KIND=4) :: LWINDM
              LOGICAL(KIND=4) :: LOGCOM(6)
            END SUBROUTINE SREDEP
          END INTERFACE 
        END MODULE SREDEP__genmod
