        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:30 2013
        MODULE SVARTP__genmod
          INTERFACE 
            SUBROUTINE SVARTP(IVTYPE)
              INTEGER(KIND=4) :: IVTYPE
            END SUBROUTINE SVARTP
          END INTERFACE 
        END MODULE SVARTP__genmod
