        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:29 2013
        MODULE SWANGRIDFACE__genmod
          INTERFACE 
            SUBROUTINE SWANGRIDFACE(NFACES,NCELLS,NVERTS,XCUGRD,YCUGRD, &
     &KVERTF)
              INTEGER(KIND=4), INTENT(IN) :: NVERTS
              INTEGER(KIND=4), INTENT(IN) :: NFACES
              INTEGER(KIND=4), INTENT(IN) :: NCELLS
              REAL(KIND=4), INTENT(IN) :: XCUGRD(NVERTS)
              REAL(KIND=4), INTENT(IN) :: YCUGRD(NVERTS)
              INTEGER(KIND=4), INTENT(IN) :: KVERTF(2,NFACES)
            END SUBROUTINE SWANGRIDFACE
          END INTERFACE 
        END MODULE SWANGRIDFACE__genmod
