        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:47 2013
        MODULE SWANGRIDTOPOLOGY__genmod
          INTERFACE 
            SUBROUTINE SWANGRIDTOPOLOGY
            END SUBROUTINE SWANGRIDTOPOLOGY
          END INTERFACE 
        END MODULE SWANGRIDTOPOLOGY__genmod
