        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:20 2013
        MODULE SWANVERTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANVERTLIST
            END SUBROUTINE SWANVERTLIST
          END INTERFACE 
        END MODULE SWANVERTLIST__genmod
