        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:33 2013
        MODULE SWANREADTRIANGLEGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADTRIANGLEGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADTRIANGLEGRID
          END INTERFACE 
        END MODULE SWANREADTRIANGLEGRID__genmod
