        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:42 2013
        MODULE SWANREADADCGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADADCGRID
            END SUBROUTINE SWANREADADCGRID
          END INTERFACE 
        END MODULE SWANREADADCGRID__genmod
