        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:26 2013
        MODULE SWANFINDOBSTACLES__genmod
          INTERFACE 
            SUBROUTINE SWANFINDOBSTACLES(CROSS)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(OUT) :: CROSS(NFACES)
            END SUBROUTINE SWANFINDOBSTACLES
          END INTERFACE 
        END MODULE SWANFINDOBSTACLES__genmod
