        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:47 2013
        MODULE SWANPRINTGRIDINFO__genmod
          INTERFACE 
            SUBROUTINE SWANPRINTGRIDINFO
            END SUBROUTINE SWANPRINTGRIDINFO
          END INTERFACE 
        END MODULE SWANPRINTGRIDINFO__genmod
