        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:31 2013
        MODULE SWANPROPVELX__genmod
          INTERFACE 
            SUBROUTINE SWANPROPVELX(CAX,CAY,UX2,UY2,CGO,ECOS,ESIN)
              USE SWCOMM3
              USE SWANGRIDDATA
              REAL(KIND=4), INTENT(OUT) :: CAX(MDC,MSC,ICMAX)
              REAL(KIND=4), INTENT(OUT) :: CAY(MDC,MSC,ICMAX)
              REAL(KIND=4), INTENT(IN) :: UX2(NVERTS)
              REAL(KIND=4), INTENT(IN) :: UY2(NVERTS)
              REAL(KIND=4), INTENT(IN) :: CGO(MSC,ICMAX)
              REAL(KIND=4), INTENT(IN) :: ECOS(MDC)
              REAL(KIND=4), INTENT(IN) :: ESIN(MDC)
            END SUBROUTINE SWANPROPVELX
          END INTERFACE 
        END MODULE SWANPROPVELX__genmod
