        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:25 2013
        MODULE SWANCREATEEDGES__genmod
          INTERFACE 
            SUBROUTINE SWANCREATEEDGES
            END SUBROUTINE SWANCREATEEDGES
          END INTERFACE 
        END MODULE SWANCREATEEDGES__genmod
