        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:41 2013
        MODULE SWANPREPCOMP__genmod
          INTERFACE 
            SUBROUTINE SWANPREPCOMP(CROSS)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(OUT) :: CROSS(NFACES)
            END SUBROUTINE SWANPREPCOMP
          END INTERFACE 
        END MODULE SWANPREPCOMP__genmod
