        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:14 2013
        MODULE SWANREADEASYMESHGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADEASYMESHGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADEASYMESHGRID
          END INTERFACE 
        END MODULE SWANREADEASYMESHGRID__genmod
