        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:16 2013
        MODULE SWANBPNTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANBPNTLIST
            END SUBROUTINE SWANBPNTLIST
          END INTERFACE 
        END MODULE SWANBPNTLIST__genmod
