        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:44 2013
        MODULE SWCOPI__genmod
          INTERFACE 
            SUBROUTINE SWCOPI(IARR1,IARR2,LENGTH)
              INTEGER(KIND=4) :: LENGTH
              INTEGER(KIND=4) :: IARR1(LENGTH)
              INTEGER(KIND=4) :: IARR2(LENGTH)
            END SUBROUTINE SWCOPI
          END INTERFACE 
        END MODULE SWCOPI__genmod
