        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWDECOMP__genmod
          INTERFACE 
            SUBROUTINE SWDECOMP
            END SUBROUTINE SWDECOMP
          END INTERFACE 
        END MODULE SWDECOMP__genmod
