        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWEXITMPI__genmod
          INTERFACE 
            SUBROUTINE SWEXITMPI
            END SUBROUTINE SWEXITMPI
          END INTERFACE 
        END MODULE SWEXITMPI__genmod
