        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:27 2013
        MODULE SWINTFXNL__genmod
          INTERFACE 
            SUBROUTINE SWINTFXNL(ASWAN,SIGMA,DIR,NDIR,NSIG,NGRID,DEPTH, &
     &IQTYPE,SNL,KCGRD,ICMAX,IERROR)
              INTEGER(KIND=4), INTENT(IN) :: ICMAX
              INTEGER(KIND=4), INTENT(IN) :: NGRID
              INTEGER(KIND=4), INTENT(IN) :: NSIG
              INTEGER(KIND=4), INTENT(IN) :: NDIR
              REAL(KIND=4), INTENT(IN) :: ASWAN(NDIR,NSIG,NGRID)
              REAL(KIND=4), INTENT(IN) :: SIGMA(NSIG)
              REAL(KIND=4), INTENT(IN) :: DIR(NDIR,6)
              REAL(KIND=4), INTENT(IN) :: DEPTH(NGRID)
              INTEGER(KIND=4), INTENT(IN) :: IQTYPE
              REAL(KIND=4), INTENT(OUT) :: SNL(NDIR,NSIG,NGRID)
              INTEGER(KIND=4), INTENT(IN) :: KCGRD(ICMAX)
              INTEGER(KIND=4), INTENT(OUT) :: IERROR
            END SUBROUTINE SWINTFXNL
          END INTERFACE 
        END MODULE SWINTFXNL__genmod
