        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWINITMPI__genmod
          INTERFACE 
            SUBROUTINE SWINITMPI
            END SUBROUTINE SWINITMPI
          END INTERFACE 
        END MODULE SWINITMPI__genmod
