        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:14 2013
        MODULE SWMAIN__genmod
          INTERFACE 
            SUBROUTINE SWMAIN
            END SUBROUTINE SWMAIN
          END INTERFACE 
        END MODULE SWMAIN__genmod
