        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWPARTIT__genmod
          INTERFACE 
            SUBROUTINE SWPARTIT(IPOWN,MXC,MYC)
              USE M_PARALL
              INTEGER(KIND=4) :: MYC
              INTEGER(KIND=4) :: MXC
              INTEGER(KIND=4) :: IPOWN(MXC,MYC)
            END SUBROUTINE SWPARTIT
          END INTERFACE 
        END MODULE SWPARTIT__genmod
