        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:35 2013
        MODULE SWPRSET__genmod
          INTERFACE 
            SUBROUTINE SWPRSET(SPCSIG)
              USE SWCOMM3
              REAL(KIND=4) :: SPCSIG(MSC)
            END SUBROUTINE SWPRSET
          END INTERFACE 
        END MODULE SWPRSET__genmod
