        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWRECVNB__genmod
          INTERFACE 
            SUBROUTINE SWRECVNB(IPTR,ILEN,ITYPE,ISOURCE,ITAG)
              INTEGER(KIND=4) :: IPTR
              INTEGER(KIND=4) :: ILEN
              INTEGER(KIND=4) :: ITYPE
              INTEGER(KIND=4) :: ISOURCE
              INTEGER(KIND=4) :: ITAG
            END SUBROUTINE SWRECVNB
          END INTERFACE 
        END MODULE SWRECVNB__genmod
