        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:30 2013
        MODULE SWREOQ__genmod
          INTERFACE 
            SUBROUTINE SWREOQ(FOUND)
              LOGICAL(KIND=4) :: FOUND
            END SUBROUTINE SWREOQ
          END INTERFACE 
        END MODULE SWREOQ__genmod
