        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWREDUCI__genmod
          INTERFACE 
            SUBROUTINE SWREDUCI(IARR,ILEN,ITYPRD)
              INTEGER(KIND=4) :: ILEN
              INTEGER(KIND=4) :: IARR(ILEN)
              INTEGER(KIND=4) :: ITYPRD
            END SUBROUTINE SWREDUCI
          END INTERFACE 
        END MODULE SWREDUCI__genmod
