        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWSENDAC__genmod
          INTERFACE 
            SUBROUTINE SWSENDAC(AC2,IE,J,SWPDIR,KGRPNT)
              USE SWCOMM3
              REAL(KIND=4) :: AC2(MDC,MSC,MCGRD)
              INTEGER(KIND=4) :: IE
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: SWPDIR
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
            END SUBROUTINE SWSENDAC
          END INTERFACE 
        END MODULE SWSENDAC__genmod
