        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:39 2013
        MODULE SWSENDNB__genmod
          INTERFACE 
            SUBROUTINE SWSENDNB(IPTR,ILEN,ITYPE,IDEST,ITAG)
              INTEGER(KIND=4) :: IPTR
              INTEGER(KIND=4) :: ILEN
              INTEGER(KIND=4) :: ITYPE
              INTEGER(KIND=4) :: IDEST
              INTEGER(KIND=4) :: ITAG
            END SUBROUTINE SWSENDNB
          END INTERFACE 
        END MODULE SWSENDNB__genmod
