        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 24 17:03:43 2013
        MODULE WRSPEC__genmod
          INTERFACE 
            SUBROUTINE WRSPEC(NREF,ACLOC)
              USE SWCOMM3
              INTEGER(KIND=4), INTENT(IN) :: NREF
              REAL(KIND=4), INTENT(IN) :: ACLOC(1:MDC,1:MSC)
            END SUBROUTINE WRSPEC
          END INTERFACE 
        END MODULE WRSPEC__genmod
