        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:31 2013
        MODULE BUGFIX__genmod
          INTERFACE 
            SUBROUTINE BUGFIX(FIXABC)
              CHARACTER(LEN=1), INTENT(IN) :: FIXABC
            END SUBROUTINE BUGFIX
          END INTERFACE 
        END MODULE BUGFIX__genmod
