        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:33 2013
        MODULE ERRCHK__genmod
          INTERFACE 
            SUBROUTINE ERRCHK
            END SUBROUTINE ERRCHK
          END INTERFACE 
        END MODULE ERRCHK__genmod
