        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:42 2013
        MODULE PUTKAR__genmod
          INTERFACE 
            SUBROUTINE PUTKAR(LTEXT,KARR,JKAR)
              CHARACTER(*) :: LTEXT
              CHARACTER(LEN=1) :: KARR
              INTEGER(KIND=4) :: JKAR
            END SUBROUTINE PUTKAR
          END INTERFACE 
        END MODULE PUTKAR__genmod
