        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:42 2013
        MODULE RDINIT__genmod
          INTERFACE 
            SUBROUTINE RDINIT
            END SUBROUTINE RDINIT
          END INTERFACE 
        END MODULE RDINIT__genmod
