        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:40 2013
        MODULE SINPGR__genmod
          INTERFACE 
            SUBROUTINE SINPGR(IGRID1,IGRID2,SNAMEG)
              INTEGER(KIND=4) :: IGRID1
              INTEGER(KIND=4) :: IGRID2
              CHARACTER(LEN=8) :: SNAMEG
            END SUBROUTINE SINPGR
          END INTERFACE 
        END MODULE SINPGR__genmod
