        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:31 2013
        MODULE STRACE__genmod
          INTERFACE 
            SUBROUTINE STRACE(IENT,SUBNAM)
              INTEGER(KIND=4) :: IENT
              CHARACTER(*) :: SUBNAM
            END SUBROUTINE STRACE
          END INTERFACE 
        END MODULE STRACE__genmod
