        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:38 2013
        MODULE SWANVERTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANVERTLIST
            END SUBROUTINE SWANVERTLIST
          END INTERFACE 
        END MODULE SWANVERTLIST__genmod
