        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:43 2013
        MODULE SWANINTERPOLATEOUTPUT__genmod
          INTERFACE 
            SUBROUTINE SWANINTERPOLATEOUTPUT(FOUTP,X,Y,FINP,MIP,KVERT,  &
     &EXCVAL)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(IN) :: MIP
              REAL(KIND=4), INTENT(OUT) :: FOUTP(MIP)
              REAL(KIND=4), INTENT(IN) :: X(MIP)
              REAL(KIND=4), INTENT(IN) :: Y(MIP)
              REAL(KIND=4), INTENT(IN) :: FINP(NVERTS)
              INTEGER(KIND=4), INTENT(IN) :: KVERT(MIP)
              REAL(KIND=4), INTENT(IN) :: EXCVAL
            END SUBROUTINE SWANINTERPOLATEOUTPUT
          END INTERFACE 
        END MODULE SWANINTERPOLATEOUTPUT__genmod
