        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:31 2013
        MODULE SWANCONVACCUR__genmod
          INTERFACE 
            SUBROUTINE SWANCONVACCUR(ACCUR,HSCURR,TMCURR,DELHS,DELTM,   &
     &XYTST,SPCSIG,AC2,IVLOW,IVUP)
              USE SWCOMM4
              USE SWCOMM3
              USE SWANGRIDDATA
              REAL(KIND=4), INTENT(OUT) :: ACCUR
              REAL(KIND=4), INTENT(INOUT) :: HSCURR(NVERTS)
              REAL(KIND=4), INTENT(INOUT) :: TMCURR(NVERTS)
              REAL(KIND=4), INTENT(OUT) :: DELHS(NVERTS)
              REAL(KIND=4), INTENT(OUT) :: DELTM(NVERTS)
              INTEGER(KIND=4), INTENT(IN) :: XYTST(NPTST)
              REAL(KIND=4), INTENT(IN) :: SPCSIG(MSC)
              REAL(KIND=4), INTENT(IN) :: AC2(MDC,MSC,NVERTS)
              INTEGER(KIND=4), INTENT(IN) :: IVLOW
              INTEGER(KIND=4), INTENT(IN) :: IVUP
            END SUBROUTINE SWANCONVACCUR
          END INTERFACE 
        END MODULE SWANCONVACCUR__genmod
