        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:49 2013
        MODULE SWANPREPCOMP__genmod
          INTERFACE 
            SUBROUTINE SWANPREPCOMP(CROSS)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(OUT) :: CROSS(NFACES)
            END SUBROUTINE SWANPREPCOMP
          END INTERFACE 
        END MODULE SWANPREPCOMP__genmod
