        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:43 2013
        MODULE SWANCREATEEDGES__genmod
          INTERFACE 
            SUBROUTINE SWANCREATEEDGES
            END SUBROUTINE SWANCREATEEDGES
          END INTERFACE 
        END MODULE SWANCREATEEDGES__genmod
