        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:44 2013
        MODULE SWANBPNTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANBPNTLIST
            END SUBROUTINE SWANBPNTLIST
          END INTERFACE 
        END MODULE SWANBPNTLIST__genmod
