        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:30 2013
        MODULE SWANINITCOMPGRID__genmod
          INTERFACE 
            SUBROUTINE SWANINITCOMPGRID(LOGCOM)
              LOGICAL(KIND=4), INTENT(INOUT) :: LOGCOM(6)
            END SUBROUTINE SWANINITCOMPGRID
          END INTERFACE 
        END MODULE SWANINITCOMPGRID__genmod
