        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:30 2013
        MODULE SWANREADADCGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADADCGRID
            END SUBROUTINE SWANREADADCGRID
          END INTERFACE 
        END MODULE SWANREADADCGRID__genmod
