        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:33 2013
        MODULE SWANTRANSPX__genmod
          INTERFACE 
            SUBROUTINE SWANTRANSPX(AMAT,RHS,AC2,AC1,CAX,CAY,RDX,RDY,    &
     &OBREDF,IDCMIN,IDCMAX,ISSLOW,ISSTOP,TRAC0,TRAC1)
              USE SWANGRIDDATA
              USE SWCOMM3
              REAL(KIND=4), INTENT(INOUT) :: AMAT(MDC,MSC,5)
              REAL(KIND=4), INTENT(INOUT) :: RHS(MDC,MSC)
              REAL(KIND=4), INTENT(IN) :: AC2(MDC,MSC,NVERTS)
              REAL(KIND=4), INTENT(IN) :: AC1(MDC,MSC,NVERTS)
              REAL(KIND=4), INTENT(IN) :: CAX(MDC,MSC,ICMAX)
              REAL(KIND=4), INTENT(IN) :: CAY(MDC,MSC,ICMAX)
              REAL(KIND=4), INTENT(IN) :: RDX(2)
              REAL(KIND=4), INTENT(IN) :: RDY(2)
              REAL(KIND=4), INTENT(IN) :: OBREDF(MDC,MSC,2)
              INTEGER(KIND=4), INTENT(IN) :: IDCMIN(MSC)
              INTEGER(KIND=4), INTENT(IN) :: IDCMAX(MSC)
              INTEGER(KIND=4), INTENT(IN) :: ISSLOW
              INTEGER(KIND=4), INTENT(IN) :: ISSTOP
              REAL(KIND=4), INTENT(OUT) :: TRAC0(MDC,MSC,3)
              REAL(KIND=4), INTENT(OUT) :: TRAC1(MDC,MSC,3)
            END SUBROUTINE SWANTRANSPX
          END INTERFACE 
        END MODULE SWANTRANSPX__genmod
