        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:40 2013
        MODULE SWCAP__genmod
          INTERFACE 
            SUBROUTINE SWCAP(SPCDIR,SPCSIG,KWAVE,AC2,IDCMIN,IDCMAX,     &
     &ISSTOP,ETOT,IMATDA,IMATRA,PLWCAP,CGO,UFRIC,DEP2,DISSC1,DISSC0)
              USE SWCOMM3
              USE SWCOMM4
              REAL(KIND=4), INTENT(IN) :: SPCDIR(MDC,6)
              REAL(KIND=4), INTENT(IN) :: SPCSIG(MSC)
              REAL(KIND=4), INTENT(IN) :: KWAVE(MSC,10)
              REAL(KIND=4), INTENT(IN) :: AC2(MDC,MSC,MCGRD)
              INTEGER(KIND=4), INTENT(IN) :: IDCMIN(MSC)
              INTEGER(KIND=4), INTENT(IN) :: IDCMAX(MSC)
              INTEGER(KIND=4), INTENT(IN) :: ISSTOP
              REAL(KIND=4), INTENT(IN) :: ETOT
              REAL(KIND=4), INTENT(INOUT) :: IMATDA(MDC,MSC)
              REAL(KIND=4), INTENT(INOUT) :: IMATRA(MDC,MSC)
              REAL(KIND=4), INTENT(OUT) :: PLWCAP(MDC,MSC,NPTST)
              REAL(KIND=4), INTENT(IN) :: CGO(MSC,10)
              REAL(KIND=4), INTENT(IN) :: UFRIC
              REAL(KIND=4), INTENT(IN) :: DEP2(MCGRD)
              REAL(KIND=4), INTENT(INOUT) :: DISSC1(MDC,MSC,3)
              REAL(KIND=4), INTENT(INOUT) :: DISSC0(MDC,MSC,3)
            END SUBROUTINE SWCAP
          END INTERFACE 
        END MODULE SWCAP__genmod
