        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:33 2013
        MODULE SWCLME__genmod
          INTERFACE 
            SUBROUTINE SWCLME
            END SUBROUTINE SWCLME
          END INTERFACE 
        END MODULE SWCLME__genmod
