        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:48 2013
        MODULE SWCOLLECT__genmod
          INTERFACE 
            SUBROUTINE SWCOLLECT(FIELDGL,FIELD,FULL)
              USE M_PARALL
              REAL(KIND=4) :: FIELDGL(*)
              REAL(KIND=4) :: FIELD(*)
              LOGICAL(KIND=4) :: FULL
            END SUBROUTINE SWCOLLECT
          END INTERFACE 
        END MODULE SWCOLLECT__genmod
