        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:48 2013
        MODULE SWDECOMP__genmod
          INTERFACE 
            SUBROUTINE SWDECOMP
            END SUBROUTINE SWDECOMP
          END INTERFACE 
        END MODULE SWDECOMP__genmod
