        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:48 2013
        MODULE SWEXITMPI__genmod
          INTERFACE 
            SUBROUTINE SWEXITMPI
            END SUBROUTINE SWEXITMPI
          END INTERFACE 
        END MODULE SWEXITMPI__genmod
