        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:44 2013
        MODULE SWREPS__genmod
          INTERFACE 
            SUBROUTINE SWREPS(FOUND,BOTLEV,WATLEV)
              LOGICAL(KIND=4) :: FOUND
              REAL(KIND=4) :: BOTLEV(*)
              REAL(KIND=4) :: WATLEV(*)
            END SUBROUTINE SWREPS
          END INTERFACE 
        END MODULE SWREPS__genmod
