        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:40 2013
        MODULE SWREAD__genmod
          INTERFACE 
            SUBROUTINE SWREAD(COMPUT)
              CHARACTER(*) :: COMPUT
            END SUBROUTINE SWREAD
          END INTERFACE 
        END MODULE SWREAD__genmod
