        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 16 14:49:42 2013
        MODULE UPCASE__genmod
          INTERFACE 
            SUBROUTINE UPCASE(CHARST)
              CHARACTER(*) :: CHARST
            END SUBROUTINE UPCASE
          END INTERFACE 
        END MODULE UPCASE__genmod
