        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE ANGRAD__genmod
          INTERFACE 
            FUNCTION ANGRAD(DEGREE) RESULT(ANGRAD_0)
              REAL(KIND=4) :: DEGREE
              REAL(KIND=4) :: ANGRAD_0
            END FUNCTION ANGRAD
          END INTERFACE 
        END MODULE ANGRAD__genmod
