        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:57 2012
        MODULE CGBOUN__genmod
          INTERFACE 
            SUBROUTINE CGBOUN(KGRPNT,KGRBND)
              USE SWCOMM3
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
              INTEGER(KIND=4) :: KGRBND(*)
            END SUBROUTINE CGBOUN
          END INTERFACE 
        END MODULE CGBOUN__genmod
