        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:04 2012
        MODULE COPYCH__genmod
          INTERFACE 
            SUBROUTINE COPYCH(STRING,MOVE,IARRAY,LENARR,IERR)
              CHARACTER(*) :: STRING
              CHARACTER(LEN=1) :: MOVE
              INTEGER(KIND=4) :: IARRAY(*)
              INTEGER(KIND=4) :: LENARR
              INTEGER(KIND=4) :: IERR
            END SUBROUTINE COPYCH
          END INTERFACE 
        END MODULE COPYCH__genmod
