        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE CVCHEK__genmod
          INTERFACE 
            SUBROUTINE CVCHEK(KGRPNT,XCGRID,YCGRID)
              USE SWCOMM3
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
              REAL(KIND=4) :: XCGRID(MXC,MYC)
              REAL(KIND=4) :: YCGRID(MXC,MYC)
            END SUBROUTINE CVCHEK
          END INTERFACE 
        END MODULE CVCHEK__genmod
