        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE DEGCNV__genmod
          INTERFACE 
            FUNCTION DEGCNV(DEGREE) RESULT(DEGCNV_0)
              REAL(KIND=4) :: DEGREE
              REAL(KIND=4) :: DEGCNV_0
            END FUNCTION DEGCNV
          END INTERFACE 
        END MODULE DEGCNV__genmod
