        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:03 2012
        MODULE DTINTI__genmod
          INTERFACE 
            SUBROUTINE DTINTI(TIMESC,INTTIM)
              REAL(KIND=4) :: TIMESC
              INTEGER(KIND=4) :: INTTIM(6)
            END SUBROUTINE DTINTI
          END INTERFACE 
        END MODULE DTINTI__genmod
