        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE DTTIST__genmod
          INTERFACE 
            SUBROUTINE DTTIST(IOPT,TIMSTR,DTTIME)
              INTEGER(KIND=4) :: IOPT
              CHARACTER(LEN=24) :: TIMSTR
              INTEGER(KIND=4) :: DTTIME(6)
            END SUBROUTINE DTTIST
          END INTERFACE 
        END MODULE DTTIST__genmod
