        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:03 2012
        MODULE DTTIWR__genmod
          INTERFACE 
            FUNCTION DTTIWR(IOPT,TIMESC) RESULT(DTTIWR_0)
              INTEGER(KIND=4) :: IOPT
              REAL(KIND=4) :: TIMESC
              CHARACTER(LEN=18) :: DTTIWR_0
            END FUNCTION DTTIWR
          END INTERFACE 
        END MODULE DTTIWR__genmod
