        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:03 2012
        MODULE DTTIME__genmod
          INTERFACE 
            FUNCTION DTTIME(INTTIM) RESULT(DTTIME_0)
              INTEGER(KIND=4) :: INTTIM(6)
              REAL(KIND=4) :: DTTIME_0
            END FUNCTION DTTIME
          END INTERFACE 
        END MODULE DTTIME__genmod
