        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE INTSTR__genmod
          INTERFACE 
            FUNCTION INTSTR(IVAL) RESULT(INTSTR_0)
              INTEGER(KIND=4) :: IVAL
              CHARACTER(LEN=20) :: INTSTR_0
            END FUNCTION INTSTR
          END INTERFACE 
        END MODULE INTSTR__genmod
