        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:04 2012
        MODULE LSPLIT__genmod
          INTERFACE 
            SUBROUTINE LSPLIT(RELINE,DATITM,NUMITM)
              INTEGER(KIND=4), INTENT(IN) :: NUMITM
              CHARACTER(*), INTENT(IN) :: RELINE
              CHARACTER(*), INTENT(OUT) :: DATITM(NUMITM)
            END SUBROUTINE LSPLIT
          END INTERFACE 
        END MODULE LSPLIT__genmod
