        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE OBSTMOVE__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE OBSTMOVE(XCGRID,YCGRID,KGRPNT)
              USE SWCOMM3
              REAL(KIND=4) :: XCGRID(MXC,MYC)
              REAL(KIND=4) :: YCGRID(MXC,MYC)
              INTEGER(KIND=4) :: KGRPNT(MXC,MYC)
            END SUBROUTINE OBSTMOVE
          END INTERFACE 
        END MODULE OBSTMOVE__genmod
