        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE RDINIT__genmod
          INTERFACE 
            SUBROUTINE RDINIT
            END SUBROUTINE RDINIT
          END INTERFACE 
        END MODULE RDINIT__genmod
