        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:01 2012
        MODULE SPROUT__genmod
          INTERFACE 
            SUBROUTINE SPROUT(FOUND,BOTLEV,WATLEV)
              LOGICAL(KIND=4) :: FOUND
              REAL(KIND=4) :: BOTLEV(*)
              REAL(KIND=4) :: WATLEV(*)
            END SUBROUTINE SPROUT
          END INTERFACE 
        END MODULE SPROUT__genmod
