        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:05 2012
        MODULE SWANREADGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADGRID
          END INTERFACE 
        END MODULE SWANREADGRID__genmod
