        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE SWANFINDOBSTACLES__genmod
          INTERFACE 
            SUBROUTINE SWANFINDOBSTACLES(CROSS)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(OUT) :: CROSS(NFACES)
            END SUBROUTINE SWANFINDOBSTACLES
          END INTERFACE 
        END MODULE SWANFINDOBSTACLES__genmod
