        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:59 2012
        MODULE SWANREADTRIANGLEGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADTRIANGLEGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADTRIANGLEGRID
          END INTERFACE 
        END MODULE SWANREADTRIANGLEGRID__genmod
