        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWANTHREADBOUNDS__genmod
          INTERFACE 
            SUBROUTINE SWANTHREADBOUNDS(NWETP,IVLOW,IVUP,TLIST)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(IN) :: NWETP
              INTEGER(KIND=4), INTENT(OUT) :: IVLOW
              INTEGER(KIND=4), INTENT(OUT) :: IVUP
              INTEGER(KIND=4), INTENT(OUT) :: TLIST(NVERTS)
            END SUBROUTINE SWANTHREADBOUNDS
          END INTERFACE 
        END MODULE SWANTHREADBOUNDS__genmod
