        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE SWANFINDPOINT__genmod
          INTERFACE 
            SUBROUTINE SWANFINDPOINT(X,Y,KVERT)
              REAL(KIND=4), INTENT(IN) :: X
              REAL(KIND=4), INTENT(IN) :: Y
              INTEGER(KIND=4), INTENT(OUT) :: KVERT
            END SUBROUTINE SWANFINDPOINT
          END INTERFACE 
        END MODULE SWANFINDPOINT__genmod
