        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:59 2012
        MODULE SWANPRINTGRIDINFO__genmod
          INTERFACE 
            SUBROUTINE SWANPRINTGRIDINFO
            END SUBROUTINE SWANPRINTGRIDINFO
          END INTERFACE 
        END MODULE SWANPRINTGRIDINFO__genmod
