        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE SWANPREPCOMP__genmod
          INTERFACE 
            SUBROUTINE SWANPREPCOMP(CROSS)
              USE SWANGRIDDATA
              INTEGER(KIND=4), INTENT(OUT) :: CROSS(NFACES)
            END SUBROUTINE SWANPREPCOMP
          END INTERFACE 
        END MODULE SWANPREPCOMP__genmod
