        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:01 2012
        MODULE SWANGRIDTOPOLOGY__genmod
          INTERFACE 
            SUBROUTINE SWANGRIDTOPOLOGY
            END SUBROUTINE SWANGRIDTOPOLOGY
          END INTERFACE 
        END MODULE SWANGRIDTOPOLOGY__genmod
