        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:56 2012
        MODULE SWANCREATEEDGES__genmod
          INTERFACE 
            SUBROUTINE SWANCREATEEDGES
            END SUBROUTINE SWANCREATEEDGES
          END INTERFACE 
        END MODULE SWANCREATEEDGES__genmod
