        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:01 2012
        MODULE SWANREADEASYMESHGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADEASYMESHGRID(BASENM,LENFNM)
              INTEGER(KIND=4), INTENT(IN) :: LENFNM
              CHARACTER(LEN=LENFNM), INTENT(IN) :: BASENM
            END SUBROUTINE SWANREADEASYMESHGRID
          END INTERFACE 
        END MODULE SWANREADEASYMESHGRID__genmod
