        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:57 2012
        MODULE SWANVERTLIST__genmod
          INTERFACE 
            SUBROUTINE SWANVERTLIST
            END SUBROUTINE SWANVERTLIST
          END INTERFACE 
        END MODULE SWANVERTLIST__genmod
