        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:05 2012
        MODULE SWANPOINTINMESH__genmod
          INTERFACE 
            FUNCTION SWANPOINTINMESH(X,Y) RESULT(SWANPOINTINMESH_0)
              REAL(KIND=4), INTENT(IN) :: X
              REAL(KIND=4), INTENT(IN) :: Y
              LOGICAL(KIND=4) :: SWANPOINTINMESH_0
            END FUNCTION SWANPOINTINMESH
          END INTERFACE 
        END MODULE SWANPOINTINMESH__genmod
