        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:56 2012
        MODULE SWANREADADCGRID__genmod
          INTERFACE 
            SUBROUTINE SWANREADADCGRID
            END SUBROUTINE SWANREADADCGRID
          END INTERFACE 
        END MODULE SWANREADADCGRID__genmod
