        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:03 2012
        MODULE SWANINITCOMPGRID__genmod
          INTERFACE 
            SUBROUTINE SWANINITCOMPGRID(LOGCOM)
              LOGICAL(KIND=4), INTENT(INOUT) :: LOGCOM(6)
            END SUBROUTINE SWANINITCOMPGRID
          END INTERFACE 
        END MODULE SWANINITCOMPGRID__genmod
