        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWBLADM__genmod
          INTERFACE 
            SUBROUTINE SWBLADM(IPOWN,MXC,MYC)
              USE M_PARALL
              INTEGER(KIND=4) :: MYC
              INTEGER(KIND=4) :: MXC
              INTEGER(KIND=4) :: IPOWN(MXC,MYC)
            END SUBROUTINE SWBLADM
          END INTERFACE 
        END MODULE SWBLADM__genmod
