        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE SWCOPI__genmod
          INTERFACE 
            SUBROUTINE SWCOPI(IARR1,IARR2,LENGTH)
              INTEGER(KIND=4) :: LENGTH
              INTEGER(KIND=4) :: IARR1(LENGTH)
              INTEGER(KIND=4) :: IARR2(LENGTH)
            END SUBROUTINE SWCOPI
          END INTERFACE 
        END MODULE SWCOPI__genmod
