        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWEXCHG__genmod
          INTERFACE 
            SUBROUTINE SWEXCHG(FIELD,KGRPNT)
              USE SWCOMM3
              REAL(KIND=4) :: FIELD(MCGRD)
              INTEGER(KIND=4) :: KGRPNT(MXC*MYC)
            END SUBROUTINE SWEXCHG
          END INTERFACE 
        END MODULE SWEXCHG__genmod
