        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWINITMPI__genmod
          INTERFACE 
            SUBROUTINE SWINITMPI
            END SUBROUTINE SWINITMPI
          END INTERFACE 
        END MODULE SWINITMPI__genmod
