        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWREDUCE__genmod
          INTERFACE 
            SUBROUTINE SWREDUCE(IPTR,ILEN,ITYPE,ITYPRD)
              INTEGER(KIND=4) :: IPTR
              INTEGER(KIND=4) :: ILEN
              INTEGER(KIND=4) :: ITYPE
              INTEGER(KIND=4) :: ITYPRD
            END SUBROUTINE SWREDUCE
          END INTERFACE 
        END MODULE SWREDUCE__genmod
