        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:00 2012
        MODULE SWREDUCR__genmod
          INTERFACE 
            SUBROUTINE SWREDUCR(ARR,ILEN,ITYPRD)
              INTEGER(KIND=4) :: ILEN
              REAL(KIND=4) :: ARR(ILEN)
              INTEGER(KIND=4) :: ITYPRD
            END SUBROUTINE SWREDUCR
          END INTERFACE 
        END MODULE SWREDUCR__genmod
