        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:04 2012
        MODULE TABHED__genmod
          INTERFACE 
            SUBROUTINE TABHED(PROGNM,LPR)
              CHARACTER(*) :: PROGNM
              INTEGER(KIND=4) :: LPR
            END SUBROUTINE TABHED
          END INTERFACE 
        END MODULE TABHED__genmod
