        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:57:55 2012
        MODULE UPCASE__genmod
          INTERFACE 
            SUBROUTINE UPCASE(CHARST)
              CHARACTER(*) :: CHARST
            END SUBROUTINE UPCASE
          END INTERFACE 
        END MODULE UPCASE__genmod
