        !COMPILER-GENERATED INTERFACE MODULE: Thu Dec 20 11:58:02 2012
        MODULE WRSPEC__genmod
          INTERFACE 
            SUBROUTINE WRSPEC(NREF,ACLOC)
              USE SWCOMM3
              INTEGER(KIND=4), INTENT(IN) :: NREF
              REAL(KIND=4), INTENT(IN) :: ACLOC(1:MDC,1:MSC)
            END SUBROUTINE WRSPEC
          END INTERFACE 
        END MODULE WRSPEC__genmod
